#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

grep -q 'name: "AgentShell"' "${project_root}/apps/AgentShell/Android.bp"
grep -q 'srcs: \["src/\*\*/\*.kt"\]' "${project_root}/apps/AgentShell/Android.bp"
grep -q 'PRODUCT_PACKAGES' "${project_root}/product/agentos_cf_x86_64.mk"
grep -q 'AgentShell' "${project_root}/product/agentos_cf_x86_64.mk"
grep -q 'AgentCapabilityService' "${project_root}/product/agentos_cf_x86_64.mk"
grep -q 'AgentVoiceService' "${project_root}/product/agentos_cf_x86_64.mk"
grep -q 'PRODUCT_PACKAGE_OVERLAYS' "${project_root}/product/agentos_cf_x86_64.mk"
grep -q 'android.intent.category.HOME' "${project_root}/apps/AgentShell/AndroidManifest.xml"
grep -q 'USE_CAPABILITY_BROKER' "${project_root}/apps/AgentShell/AndroidManifest.xml"
grep -q 'system.time.read' "${project_root}/libraries/CapabilityCore/src/com/agentos/capability/core/Capabilities.kt"
grep -q 'class CapabilityBroker' "${project_root}/libraries/CapabilityCore/src/com/agentos/capability/core/CapabilityBroker.kt"
grep -q 'interface IAgentCapabilityService' "${project_root}/libraries/CapabilityApi/src/main/aidl/com/agentos/capability/api/IAgentCapabilityService.aidl"
grep -q 'oneway interface IAgentEventListener' "${project_root}/libraries/CapabilityApi/src/main/aidl/com/agentos/capability/api/IAgentEventListener.aidl"
grep -q 'android:protectionLevel="signature"' "${project_root}/services/AgentCapabilityService/AndroidManifest.xml"
grep -q 'BIND_NOTIFICATION_LISTENER_SERVICE' "${project_root}/services/AgentCapabilityService/AndroidManifest.xml"
! grep -q 'android.permission.RECORD_AUDIO' "${project_root}/apps/AgentShell/AndroidManifest.xml"
grep -q 'android.permission.RECORD_AUDIO' "${project_root}/services/AgentVoiceService/AndroidManifest.xml"
grep -q 'BIND_HOTWORD_DETECTION_SERVICE' "${project_root}/services/AgentVoiceService/AndroidManifest.xml"
grep -q 'createAlwaysOnHotwordDetector' "${project_root}/services/AgentVoiceService/src/com/agentos/voice/AgentVoiceInteractionService.java"
grep -q 'createOnDeviceSpeechRecognizer' "${project_root}/services/AgentVoiceService/src/com/agentos/voice/AgentVoiceInteractionSession.java"
grep -q 'EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS, 1200L' "${project_root}/services/AgentVoiceService/src/com/agentos/voice/AgentVoiceInteractionSession.java"
grep -q 'MAX_LISTENING_MILLIS = 10_000L' "${project_root}/services/AgentVoiceService/src/com/agentos/voice/AgentVoiceInteractionSession.java"
grep -q 'config_forceVoiceInteractionServicePackage' "${project_root}/overlay/frameworks/base/core/res/res/values/config.xml"
grep -q 'com.agentos.voice domain=agent_voice_service' "${project_root}/sepolicy/private/seapp_contexts"
grep -q 'Binder.getCallingUid' "${project_root}/services/AgentCapabilityService/src/com/agentos/capability/service/AgentCapabilityService.kt"
grep -q 'com.agentos.capability domain=agent_capability_service' "${project_root}/sepolicy/private/seapp_contexts"
grep -q 'class OpenAiCompatiblePlanner' "${project_root}/apps/AgentShell/src/com/agentos/shell/OpenAiCompatiblePlanner.kt"
grep -q 'class GeneratedUiParser' "${project_root}/apps/AgentShell/src/com/agentos/shell/GeneratedUiParser.kt"
python3 -m json.tool "${project_root}/schemas/generated-ui.schema.json" >/dev/null

echo "AgentOS platform checks passed"
