#!/usr/bin/env bash
set -euo pipefail

project_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

grep -q 'name: "AgentShell"' "${project_root}/apps/AgentShell/Android.bp"
grep -q 'srcs: \["src/\*\*/\*.kt"\]' "${project_root}/apps/AgentShell/Android.bp"
grep -q 'asset_dirs: \["assets"\]' "${project_root}/apps/AgentShell/Android.bp"
grep -q 'PRODUCT_PACKAGES' "${project_root}/product/agentos_cf_x86_64.mk"
grep -q 'AgentShell' "${project_root}/product/agentos_cf_x86_64.mk"
grep -q 'AgentCapabilityService' "${project_root}/product/agentos_cf_x86_64.mk"
grep -q 'AgentVoiceService' "${project_root}/product/agentos_cf_x86_64.mk"
grep -q 'AgentMediaService' "${project_root}/product/agentos_cf_x86_64.mk"
grep -q 'PRODUCT_PACKAGE_OVERLAYS' "${project_root}/product/agentos_cf_x86_64.mk"
grep -q 'android.intent.category.HOME' "${project_root}/apps/AgentShell/AndroidManifest.xml"
grep -q 'USE_CAPABILITY_BROKER' "${project_root}/apps/AgentShell/AndroidManifest.xml"
grep -q 'system.time.read' "${project_root}/libraries/CapabilityCore/src/com/agentos/capability/core/Capabilities.kt"
grep -q 'class CapabilityBroker' "${project_root}/libraries/CapabilityCore/src/com/agentos/capability/core/CapabilityBroker.kt"
grep -q 'interface IAgentCapabilityService' "${project_root}/libraries/CapabilityApi/src/main/aidl/com/agentos/capability/api/IAgentCapabilityService.aidl"
grep -q 'oneway interface IAgentEventListener' "${project_root}/libraries/CapabilityApi/src/main/aidl/com/agentos/capability/api/IAgentEventListener.aidl"
grep -q 'android:protectionLevel="signature"' "${project_root}/services/AgentCapabilityService/AndroidManifest.xml"
grep -q 'BIND_NOTIFICATION_LISTENER_SERVICE' "${project_root}/services/AgentCapabilityService/AndroidManifest.xml"
grep -q 'BIND_ACCESSIBILITY_SERVICE' "${project_root}/services/AgentCapabilityService/AndroidManifest.xml"
grep -q 'interface IAgentAppBridgeService' "${project_root}/libraries/CapabilityApi/src/main/aidl/com/agentos/capability/api/IAgentAppBridgeService.aidl"
grep -q 'Binder.getCallingUid' "${project_root}/services/AgentCapabilityService/src/com/agentos/capability/service/AgentAppBridgeService.kt"
grep -q 'MAX_NODES = 200' "${project_root}/services/AgentCapabilityService/src/com/agentos/capability/service/AgentAppAccessibilityService.kt"
! grep -q 'android.permission.RECORD_AUDIO' "${project_root}/apps/AgentShell/AndroidManifest.xml"
grep -q 'android.permission.RECORD_AUDIO' "${project_root}/services/AgentVoiceService/AndroidManifest.xml"
grep -q 'android:foregroundServiceType="camera|microphone"' "${project_root}/services/AgentMediaService/AndroidManifest.xml"
grep -q 'interface IAgentMediaService' "${project_root}/libraries/CapabilityApi/src/main/aidl/com/agentos/capability/api/IAgentMediaService.aidl"
grep -q 'Binder.getCallingUid' "${project_root}/services/AgentMediaService/src/com/agentos/media/AgentMediaService.kt"
grep -q 'SurfaceView' "${project_root}/apps/AgentShell/src/com/agentos/shell/MediaWorkspace.kt"
grep -q 'fun AgentHomeScreen' "${project_root}/apps/AgentShell/src/com/agentos/shell/AgentHome.kt"
grep -q 'fun AgentBackdrop' "${project_root}/apps/AgentShell/src/com/agentos/shell/AgentDesign.kt"
grep -q 'fun CharacterStudio' "${project_root}/apps/AgentShell/src/com/agentos/shell/CharacterStudio.kt"
grep -q 'enum class AvatarExpression' "${project_root}/apps/AgentShell/src/com/agentos/shell/AgentAvatar.kt"
grep -q 'class LocalAgentAvatarStore' "${project_root}/apps/AgentShell/src/com/agentos/shell/AgentAvatar.kt"
grep -q 'class AvatarRenderer' "${project_root}/apps/AgentShell/src/com/agentos/shell/AgentAvatar3DView.kt"
grep -q 'class FullscreenQuad' "${project_root}/apps/AgentShell/src/com/agentos/shell/AgentAvatar3DView.kt"
grep -q 'class AgentAvatarWebView' "${project_root}/apps/AgentShell/src/com/agentos/shell/AgentAvatarWebView.kt"
grep -q 'blockNetworkLoads = true' "${project_root}/apps/AgentShell/src/com/agentos/shell/AgentAvatarWebView.kt"
grep -q 'allowFileAccess = false' "${project_root}/apps/AgentShell/src/com/agentos/shell/AgentAvatarWebView.kt"
! grep -q 'addJavascriptInterface' "${project_root}/apps/AgentShell/src/com/agentos/shell/AgentAvatarWebView.kt"
grep -q 'data class AvatarRenderCommand' "${project_root}/apps/AgentShell/src/com/agentos/shell/AvatarRenderCommand.kt"
grep -q 'JSON.parse' "${project_root}/apps/AgentShell/src/com/agentos/shell/AvatarRenderCommand.kt"
grep -q "default-src 'none'" "${project_root}/apps/AgentShell/assets/avatar/index.html"
grep -q 'window.AgentOSAvatar = Object.freeze' "${project_root}/apps/AgentShell/assets/avatar/runtime.js"
grep -q 'Number(input.protocol) !== PROTOCOL_VERSION' "${project_root}/apps/AgentShell/assets/avatar/runtime.js"
grep -q 'protocolSelfCheck();' "${project_root}/apps/AgentShell/assets/avatar/runtime.js"
grep -q 'data class ThoughtFieldUniformState' "${project_root}/apps/AgentShell/src/com/agentos/shell/ThoughtFieldUniformState.kt"
grep -q 'object ThoughtFieldSurfaceGeometry' "${project_root}/apps/AgentShell/src/com/agentos/shell/ThoughtFieldSurfaceGeometry.kt"
grep -q 'DEFAULT_RINGS = 64' "${project_root}/apps/AgentShell/src/com/agentos/shell/ThoughtFieldSurfaceGeometry.kt"
grep -q 'uniform vec2 uResolution' "${project_root}/apps/AgentShell/res/raw/thought_field_fragment.glsl"
grep -q 'uniform float uSurfaceLayer' "${project_root}/apps/AgentShell/res/raw/thought_field_fragment.glsl"
grep -q 'sdBezier' "${project_root}/apps/AgentShell/res/raw/thought_field_fragment.glsl"
! grep -q 'sampler2D' "${project_root}/apps/AgentShell/res/raw/thought_field_fragment.glsl"
grep -q 'attribute vec3 aParam' "${project_root}/apps/AgentShell/res/raw/thought_field_surface_vertex.glsl"
grep -q 'uniform float uLayerScale' "${project_root}/apps/AgentShell/res/raw/thought_field_surface_vertex.glsl"
grep -q 'uniform vec3 uInverseScale' "${project_root}/apps/AgentShell/res/raw/thought_field_part_vertex.glsl"
grep -q 'uniform float uSurfacePass' "${project_root}/apps/AgentShell/res/raw/thought_field_glass_fragment.glsl"
! grep -q 'sampler2D' "${project_root}/apps/AgentShell/res/raw/thought_field_glass_fragment.glsl"
grep -q "'tf_shared.glsl'" "${project_root}/apps/AgentShell/assets/avatar/runtime.js"
grep -q "'tf_strand_vertex.glsl'" "${project_root}/apps/AgentShell/res/raw/tf_shared.glsl" 2>/dev/null || true
grep -q 'float fieldWidth(float y)' "${project_root}/apps/AgentShell/res/raw/tf_shared.glsl"
grep -q 'gl_VertexID' "${project_root}/apps/AgentShell/res/raw/tf_spark_vertex.glsl"
! grep -q 'sampler2D' "${project_root}/apps/AgentShell/res/raw/tf_spark_vertex.glsl"
grep -q 'uViewProjection' "${project_root}/apps/AgentShell/res/raw/tf_strand_vertex.glsl"
grep -q 'uThreshold' "${project_root}/apps/AgentShell/res/raw/tf_bright_fragment.glsl"
grep -q 'uDown' "${project_root}/apps/AgentShell/res/raw/tf_blur_fragment.glsl"
grep -q 'uBloomStrength' "${project_root}/apps/AgentShell/res/raw/tf_composite_fragment.glsl"
grep -q "'tf_strand_vertex.glsl'" "${project_root}/apps/AgentShell/assets/avatar/runtime.js"
grep -q 'getContext(.webgl2.' "${project_root}/apps/AgentShell/assets/avatar/runtime.js"
grep -q 'RGBA16F' "${project_root}/apps/AgentShell/assets/avatar/runtime.js"
grep -q '/shaders/tf_strand_vertex.glsl' "${project_root}/apps/AgentShell/src/com/agentos/shell/AgentAvatarWebView.kt"
grep -q '/shaders/tf_glass_fragment.glsl' "${project_root}/apps/AgentShell/src/com/agentos/shell/AgentAvatarWebView.kt"
grep -q 'apps/AgentShell/assets/avatar/runtime.js' "${project_root}/scripts/thought-field-preview.html"
grep -q "'tf_glass_vertex.glsl'" "${project_root}/apps/AgentShell/assets/avatar/runtime.js"
grep -q 'createSurface(rings = 64, segments = 28)' "${project_root}/apps/AgentShell/assets/avatar/runtime.js"
grep -q 'enum class AvatarGesture' "${project_root}/apps/AgentShell/src/com/agentos/shell/AvatarPerformance.kt"
grep -q 'FRAME_DELAY_MS = 33L' "${project_root}/apps/AgentShell/src/com/agentos/shell/AgentAvatar3DView.kt"
grep -q 'class AvatarStyleParser' "${project_root}/apps/AgentShell/src/com/agentos/shell/AvatarStyleGenerator.kt"
grep -q 'object AppAdapterCatalog' "${project_root}/services/AgentCapabilityService/src/com/agentos/capability/service/AppBridgePolicy.kt"
grep -q 'BIND_HOTWORD_DETECTION_SERVICE' "${project_root}/services/AgentVoiceService/AndroidManifest.xml"
grep -q 'createAlwaysOnHotwordDetector' "${project_root}/services/AgentVoiceService/src/com/agentos/voice/AgentVoiceInteractionService.java"
grep -q 'createOnDeviceSpeechRecognizer' "${project_root}/services/AgentVoiceService/src/com/agentos/voice/AgentVoiceInteractionSession.java"
grep -q 'EXTRA_SPEECH_INPUT_COMPLETE_SILENCE_LENGTH_MILLIS, 1200L' "${project_root}/services/AgentVoiceService/src/com/agentos/voice/AgentVoiceInteractionSession.java"
grep -q 'MAX_LISTENING_MILLIS = 10_000L' "${project_root}/services/AgentVoiceService/src/com/agentos/voice/AgentVoiceInteractionSession.java"
grep -q 'ACTION_INTERRUPT_OUTPUT' "${project_root}/services/AgentVoiceService/src/com/agentos/voice/AgentVoiceInteractionService.java"
grep -q 'class LocalConversationHistory' "${project_root}/apps/AgentShell/src/com/agentos/shell/ConversationHistory.kt"
grep -q 'abstract class AgentKnowledgeDatabase : RoomDatabase' "${project_root}/apps/AgentShell/src/com/agentos/shell/ConversationHistory.kt"
grep -q 'MIGRATION_1_2' "${project_root}/apps/AgentShell/src/com/agentos/shell/ConversationHistory.kt"
grep -q 'MIGRATION_2_3' "${project_root}/apps/AgentShell/src/com/agentos/shell/ConversationHistory.kt"
grep -q 'tableName = "node_positions"' "${project_root}/apps/AgentShell/src/com/agentos/shell/ConversationHistory.kt"
grep -q 'InteractiveKnowledgeGraph' "${project_root}/apps/AgentShell/src/com/agentos/shell/KnowledgeGraphCanvas.kt"
grep -q 'transformable(transformState)' "${project_root}/apps/AgentShell/src/com/agentos/shell/KnowledgeGraphCanvas.kt"
grep -q 'detectDragGesturesAfterLongPress' "${project_root}/apps/AgentShell/src/com/agentos/shell/KnowledgeGraphCanvas.kt"
grep -q 'class ModelKnowledgeExtractor' "${project_root}/apps/AgentShell/src/com/agentos/shell/KnowledgeExtractor.kt"
grep -q 'state.history.asReversed()' "${project_root}/apps/AgentShell/src/com/agentos/shell/MainActivity.kt"
grep -q 'config_forceVoiceInteractionServicePackage' "${project_root}/overlay/frameworks/base/core/res/res/values/config.xml"
grep -q 'com.agentos.voice domain=agent_voice_service' "${project_root}/sepolicy/private/seapp_contexts"
grep -q 'Binder.getCallingUid' "${project_root}/services/AgentCapabilityService/src/com/agentos/capability/service/AgentCapabilityService.kt"
grep -q 'com.agentos.capability domain=agent_capability_service' "${project_root}/sepolicy/private/seapp_contexts"
grep -q 'class OpenAiCompatiblePlanner' "${project_root}/apps/AgentShell/src/com/agentos/shell/OpenAiCompatiblePlanner.kt"
grep -q 'class GeneratedUiParser' "${project_root}/apps/AgentShell/src/com/agentos/shell/GeneratedUiParser.kt"
python3 -m json.tool "${project_root}/schemas/generated-ui.schema.json" >/dev/null
python3 -m json.tool "${project_root}/schemas/avatar-style.schema.json" >/dev/null
bash -n "${project_root}/scripts/capture-hotword-diagnostics.sh"
bash -n "${project_root}/scripts/capture-thought-field-preview.sh"

for preview in thought-field-home-concept thought-field-studio-concept app-bridge-v2 camera-v2 knowledge-v2; do
  test -s "${project_root}/docs/images/ui-v2/${preview}.png"
done

if command -v sha256sum >/dev/null 2>&1; then
  (cd "${project_root}" && sha256sum --check docs/images/ui-v2/ui-preview.sha256)
else
  (cd "${project_root}" && shasum -a 256 --check docs/images/ui-v2/ui-preview.sha256)
fi

echo "AgentOS platform checks passed"
